import { StyleSheet } from 'react-native';
import {
  Layout,
  Colors,
  Radius,
  Shadows,
  Spacing,
  Typography,
} from '../../../shared/theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { paddingBottom: 28 },

  heroWrap: {
    width: '100%',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    // shorter, more consistent header shadow
    position: 'relative',
    // shadow removed per UX request
    shadowColor: 'transparent',
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
    zIndex: 10,
  },
  // Clipper for the hero content when shadow is applied to heroWrap
  heroClip: {
    overflow: 'hidden',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  heroBg: {
    ...StyleSheet.absoluteFillObject,
  },
  heroContent: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 18,
    alignItems: 'center',
  },
  heroAvatarWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    marginBottom: 12,
    position: 'relative',
    overflow: 'visible',
  },
  heroAvatarClip: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  heroAvatarIcon: { width: 44, height: 44, tintColor: '#ffffff' },
  heroAvatarPhoto: {
    // width and height are set dynamically based on stored imgW/imgH
  },
  heroAvatarLetter: { color: '#FFFFFF', fontSize: 34, fontWeight: '800' },
  heroEditBadge: {
    position: 'absolute',
    right: -1,
    bottom: -1,
    width: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  heroTitle: { fontSize: 24, fontWeight: '800', color: Colors.textOnPrimary, textAlign: 'center' },
  heroSubtitle: { marginTop: 6, color: 'rgba(255,255,255,0.85)', textAlign: 'center', fontSize: 13, lineHeight: 18 },

  body: {
    paddingHorizontal: 22,
    paddingTop: 18,
  },

  // Backwards-compat (some legacy styles still referenced elsewhere)
  title: { fontSize: 24, fontWeight: '700', color: Colors.text, textAlign: 'center' },
  subtitle: { marginTop: 8, marginBottom: 12, color: Colors.textSubtle, textAlign: 'center', fontSize: 14, lineHeight: 20 },
  error: { color: Colors.danger, marginBottom: 10, textAlign: 'center' },
  card: {
    backgroundColor: Colors.transparent,
    borderRadius: Radius.none,
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginBottom: 28,
    borderWidth: 0,
    borderColor: Colors.transparent,
    shadowColor: 'transparent',
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  cardDisabled: {
    backgroundColor: Colors.transparent,
  },
  lockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(243,244,246,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockIcon: {
    width: 54,
    height: 54,
    tintColor: Colors.textSubtle,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionTitle: { fontSize: Typography.bodyLg, fontWeight: '800', color: Colors.text },
  input: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    color: Colors.text,
    fontSize: 16,
    includeFontPadding: false,
  },
  inputError: {
    borderColor: Colors.danger,
    backgroundColor: Colors.dangerSoft,
  },
  inlineFieldRow: {
    position: 'relative',
    width: '100%',
    marginBottom: 12,
  },
  passwordToggle: {
    justifyContent: 'center',
    paddingHorizontal: 3,
    alignItems: 'center',
  },
  row: { flexDirection: 'row', gap: 12 },
  halfWrapper: { flex: 1, position: 'relative' },
  inlineDropdownWrap: { position: 'relative' },
  dropdownLabel: { fontSize: 14, fontWeight: '600', color: Colors.textSubtle, marginBottom: 12 },
  selectContainer: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectContainerOpen: { borderColor: Colors.primary },
  selectText: { color: Colors.text, fontSize: 15, flex: 1 },
  selectPlaceholder: { color: Colors.textDisabled },
  chevron: { marginLeft: 'auto', color: Colors.textSubtle, fontSize: 14 },
  chevronOpen: { color: Colors.primary },
  textArea: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: 16,
    paddingVertical: 10,
    lineHeight: 20,
    marginBottom: 12,
    color: Colors.text,
    fontSize: 16,
    includeFontPadding: false,
  },

  dropdownCard: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.surface,
    marginTop: -8,
    marginBottom: 12,
    overflow: 'hidden',
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  dropdownOptionFirst: { borderTopWidth: 0 },
  dropdownOptionText: { color: Colors.text, fontSize: 15 },
  selectOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  selectOptionSelected: {
    backgroundColor: Colors.gray100,
  },
  selectCheck: {
    color: Colors.primary,
    fontWeight: '900',
    fontSize: 16,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    marginBottom: 8,
  },
  switchLabel: { fontSize: 15, color: Colors.text, fontWeight: '600' },
  button: {
    marginTop: 8,
  },
  buttonText: { color: Colors.textOnPrimary, fontWeight: '700', fontSize: 16 },

  logoutButton: {
    marginTop: 12,
    backgroundColor: Colors.danger,
  },
  logoutButtonText: { color: Colors.textOnPrimary, fontWeight: '700', fontSize: 15 },

  backButton: {
    backgroundColor: Colors.surface,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 12,
    borderWidth: 1,
    borderColor: Colors.borderSoft,
  },
  backButtonText: { color: Colors.text, fontWeight: '700', fontSize: 15 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: 18,
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: Colors.text, marginBottom: 12, textAlign: 'center' },
  modalRow: { flexDirection: 'row', gap: 12, marginTop: 12 },
  modalBtn: { flex: 1, borderRadius: Radius.md, paddingVertical: 14, alignItems: 'center' },
  modalBtnPrimary: { backgroundColor: Colors.text },
  modalBtnSecondary: { backgroundColor: Colors.gray100 },
  modalBtnText: { color: Colors.textOnPrimary, fontWeight: '700', fontSize: 15 },

  avatarEditorBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  avatarEditorCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: 18,
  },
  avatarEditorTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.text,
    textAlign: 'center',
  },
  avatarEditorSub: {
    marginTop: 6,
    color: Colors.textSubtle,
    fontSize: 13,
    textAlign: 'center',
  },
  avatarEditorPreviewWrap: {
    marginTop: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditorCircle: {
    width: 240,
    height: 240,
    borderRadius: 120,
    overflow: 'hidden',
    backgroundColor: Colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditorControlsRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  avatarEditorZoomBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    backgroundColor: Colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditorZoomBtnText: {
    fontSize: 20,
    fontWeight: '900',
    color: Colors.text,
  },
  avatarEditorZoomText: {
    minWidth: 60,
    textAlign: 'center',
    fontWeight: '800',
    color: Colors.text,
  },
  avatarEditorResetBtn: {
    paddingHorizontal: 12,
    height: 40,
    borderRadius: Radius.md,
    backgroundColor: Colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEditorResetText: {
    fontWeight: '800',
    color: Colors.text,
  },
  avatarEditorButtonsRow: {
    marginTop: 16,
    flexDirection: 'row',
    gap: 12,
  },
  avatarEditorBtn: {
    flex: 1,
    borderRadius: Radius.md,
    paddingVertical: 14,
    alignItems: 'center',
  },
  avatarEditorBtnPrimary: {
    backgroundColor: Colors.primary,
  },
  avatarEditorBtnSecondary: {
    backgroundColor: Colors.gray100,
  },
  avatarEditorBtnPrimaryText: {
    color: Colors.textOnPrimary,
    fontWeight: '800',
  },
  avatarEditorBtnSecondaryText: {
    color: Colors.text,
    fontWeight: '800',
  },
  modalBtnTextSecondary: { color: Colors.text },
});

export default styles;
