import type { LegalSection } from '../../../shared/components/LegalSections';

export const TERMS_OF_SERVICE_SECTIONS: LegalSection[] = [
  {
    number: 1,
    title: 'User Eligibility',
    paragraphs: [
      'You must be at least eighteen (18) years of age or otherwise have legal capacity under the laws of Thailand in order to use this application. By accessing or using the application, you represent and warrant that you meet the foregoing eligibility requirements.',
    ],
  },
  {
    number: 2,
    title: 'Application Description',
    paragraphs: [
      'This application provides tools for users to:',
      'This application is intended for general health tracking and informational purposes only.',
    ],
    bullets: [
      'Record, store, and display personal health information',
      'Display information received from compatible health or medical devices',
      'Receive alerts or automated notifications generated from such information',
    ],
  },
  {
    number: 3,
    title: 'Paid Features and Free Trial Period',
    paragraphs: [
      'The application may include both free features and paid features. You may be granted access to all or some paid features during a free trial period of thirty (30) days without the need to provide a payment method, unless otherwise specified within the application.',
      'Upon expiration of the free trial, access to certain features, system functions, or data storage may be limited, suspended, or terminated unless you subscribe to or purchase an applicable paid package.',
      'Details regarding packages, features, duration, and pricing will be shown within the application and may change from time to time.',
    ],
  },
  {
    number: 4,
    title: 'Not Medical Advice',
    paragraphs: [
      'This application does not provide medical advice, diagnosis, or treatment. Any data, text, analysis, alerts, or notifications generated by the application are provided for informational purposes only and are not a substitute for professional medical advice, diagnosis, or treatment.',
      'You should always consult a qualified healthcare professional regarding symptoms, illness, or any health-related decisions.',
    ],
  },
  {
    number: 5,
    title: 'Health Alerts and Limitations',
    paragraphs: [
      'The application may generate automated alerts, including but not limited to alerts relating to health indicators, based on information you provide or information received from connected devices.',
      'You acknowledge and agree that:',
    ],
    bullets: [
      'Alerts are generated automatically and may be inaccurate, incomplete, delayed, or unavailable',
      'Device readings may be inconsistent, inaccurate, or affected by technical limitations',
      'The application is not designed for emergency use',
      'You should not rely solely on alerts for medical decisions or emergency situations',
      'The Company will not be liable for any act or omission found to arise from reliance on such alerts',
    ],
  },
  {
    number: 6,
    title: 'User Responsibilities',
    paragraphs: [
      'You agree that:',
      'The Company will not be responsible for any impacts arising from inaccurate, incomplete, or outdated information provided by you.',
    ],
    bullets: [
      'You have read and acknowledged the Company’s privacy policy as published in the application and understand it. The Company reserves the right to update and amend the privacy policy from time to time; therefore, you should review it regularly. The Company may provide additional written notice via the application for material changes by a method the Company deems appropriate',
      'You agree to provide necessary personal data to the Company for purposes related to use of the application under these Terms. You acknowledge that failure to provide personal data may affect the Company’s ability to assess or process information for the purposes of these Terms',
      'You represent and warrant that any information you provide to the Company (including personal data) is accurate, complete, and up to date. If any changes occur, you will notify the Company accordingly',
      'If you provide another person’s personal data to the Company, you represent that:',
      '(a) the data subject has been informed of the collection, use, disclosure, and/or transfer of personal data domestically or internationally under these Terms;',
      '(b) you have obtained consent or have another lawful basis as stated in the Company’s privacy policy (as applicable) for such processing and/or transfer as required by personal data protection laws; and',
      '(c) you have the right to disclose such personal data to the Company, resulting in the Company having the right to collect, use, disclose, and/or transfer the data for the purposes of these Terms and the relevant privacy policy.',
      'You will use the application for lawful purposes and in compliance with these Terms',
      'You will not misuse the application or attempt to interfere with the operation, security, or integrity of the system',
    ],
  },
  {
    number: 7,
    title: 'Account Use and Security',
    paragraphs: ['Where account registration is required:'],
    bullets: [
      'You are responsible for maintaining the confidentiality of your login credentials',
      'You are responsible for all activities under your account',
      'You agree to promptly notify the Company if you suspect unauthorized use of your account',
    ],
  },
  {
    number: 8,
    title: 'Intellectual Property Rights',
    paragraphs: [
      'All intellectual property created from development such as content, software, trademarks, logos, and other media appearing in the application, including the app name, app icon, and the Company’s logo shall be owned by the Company and protected under applicable intellectual property laws, unless otherwise stated.',
      'Certain intellectual property (e.g., icons, images, or certain visual media) used in the application may originate from third-party providers and be used under their respective license terms. All rights that belonged to each party prior to execution of this document (e.g., patents, copyrights, trademarks, or trade secrets) remain the exclusive property of that party. No party may authorize the other to use such intellectual property.',
      'The Company grants you a limited, non-exclusive, non-transferable, revocable license to use the application for personal and non-commercial purposes only, subject to these Terms.',
    ],
  },
  {
    number: 9,
    title: 'Suspension or Termination',
    paragraphs: [
      'We reserve the right, at our sole discretion, to suspend or terminate your access to the application in whole or in part at any time, including where:',
      'The Company may terminate access immediately without prior notice. You agree to compensate the Company for actual damages incurred, including increased expenses, if such breach results from your actions.',
    ],
    bullets: [
      'You breach these Terms',
      'You misuse the application or use it inappropriately',
      'Suspension/termination is necessary for legal, security, or operational reasons',
      'You breach representations under these Terms or take any action constituting a breach',
    ],
  },
  {
    number: 10,
    title: 'Third-Party Services and Devices',
    paragraphs: [
      'The App may integrate with, display data from, or rely on third-party services, platforms, or devices, including health or medical devices. The Company does not control and shall not be responsible or liable for the availability, accuracy, performance, operation, or reliability of any such third-party services or devices. Your use of any third-party services or devices is subject to the terms and conditions of the respective third parties.',
    ],
  },
  {
    number: 11,
    title: 'Disclaimer of Warranties',
    paragraphs: [
      'The App is provided on an “as is” and “as available” basis. To the fullest extent permitted by law, we disclaim all warranties, whether express or implied, including but not limited to warranties of accuracy, reliability, merchantability, fitness for a particular purpose, and non-infringement.',
      'We do not warrant that :',
    ],
    bullets: [
      'The App will be uninterrupted, secure, or error-free',
      'Any data or alerts will be accurate, complete, or reliable',
      'The App will meet your specific requirements or expectations',
    ],
  },
  {
    number: 12,
    title: 'Limitation of Liability',
    paragraphs: [
      'To the maximum extent permitted by applicable law, the Company shall not be liable for any direct or indirect damages, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, or bodily injury arising from or relating to the use of, or reliance on, the application, information, or alerts.',
    ],
  },
  {
    number: 13,
    title: 'Privacy / Confidentiality',
    paragraphs: [
      'Personal data collected through the application will be processed in accordance with the Company’s privacy policy, which is prepared separately and forms part of these Terms. Processing of certain types of data may require explicit consent, which will be requested separately within the application as required by law.',
    ],
  },
  {
    number: 14,
    title: 'Changes to the Terms',
    paragraphs: ['The Company may amend or update these Terms from time to time. Continued use of the application after changes take effect constitutes your acceptance of the revised Terms.'],
  },
  {
    number: 15,
    title: 'Governing Law',
    paragraphs: ['These Terms shall be governed by and construed in accordance with the laws of the Kingdom of Thailand, without regard to conflict of law principles.'],
  },
  {
    number: 16,
    title: 'Contact Information',
    paragraphs: [
      'If you have questions about these Terms, please contact:',
      'BPS Technology Public Company Limited',
      '25/34–38, 47–51 Sukhumvit Road',
      'Pak Nam Subdistrict, Mueang Samut Prakan District',
      'Samut Prakan 10270, Thailand',
      'Tel: 02 755 2688',
    ],
  },
];
